# Generated by Django 3.1 on 2020-08-21 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roastboastmodel',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
